export enum CategoryEnum {
  // categories that could be used for a product by any retailer

  Wine = 'Wine',
  Beer = 'Beer',
  Spirits = 'Spirits',
  Liquor = 'Liquor',
  Scotch = 'Scotch',
  Vodka = 'Vodka',
  Gin = 'Gin',
  Rum = 'Rum',
  Tequila = 'Tequila',
  Brandy = 'Brandy',
  OtherDrinks = 'OtherDrinks',
  Electronics = 'Electronics',
  Computers = 'Computers',
  Tablets = 'Tablets',
  Smartphones = 'Smartphones',
  Laptops = 'Laptops',
  OtherElectronics = 'OtherElectronics',
  Food = 'Food',
  Books = 'Books',
  Movies = 'Movies',
  Magazine = 'Magazine',
  Furniture = 'Furniture',
  OtherFurniture = 'OtherFurniture',
  Other = 'Other',
  Appliances = 'Appliances',
  Medicine = 'Medicine',
}
