export enum CategoryEnum {
  AlcoholDrinks = 'AlcoholDrinks',
  NonAlcoholDrinks = 'NonAlcoholDrinks',
  Food = 'Food',
  Electronics = 'Electronics',
  Computers = 'Computers',
  Tablets = 'Tablets',
  Smartphones = 'Smartphones',
  Laptops = 'Laptops',
  OtherElectronics = 'OtherElectronics',
  Books = 'Books',
  Movies = 'Movies',
  Magazine = 'Magazine',
  Furniture = 'Furniture',
  OtherFurniture = 'OtherFurniture',
  Other = 'Other',
  Appliances = 'Appliances',
  Medicine = 'Medicine',
  Clothing = 'Clothing',
  Shoes = 'Shoes',
  Accessories = 'Accessories',

  Null = 'Null',
}
