# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - ng-solid-retail

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  workflow_dispatch:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
env:
  ACTIONS_RUNNER_DEBUG: true

jobs:
  lint_test_build_affected:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true
      DOTNET_GENERATE_ASPNET_CERTIFICATE: false
      DOTNET_ADD_GLOBAL_TOOLS_TO_PATH: false
      DOTNET_MULTILEVEL_LOOKUP: 0

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x'
          include-prerelease: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        # with:
        #   cache: 'yarn'

      - name: Set up Nx
        uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: 'master'

      # - name: remove bin and obj folders
      #   run: find . -iname "bin" -o -iname "obj" | xargs rm -rf

      # - name: rm -rf node_modules
      #   run: rm -rf node_modules .angular && yarn cache clean --force && npm cache verify

      - name: Install Nx dependencies
        run: yarn install --frozen-lockfile

      - name: reset
        run: npx nx reset

      - name: Lint all
        run: npx nx run-many --target=lint --parallel=3

      - name: Test all
        run: npx nx run-many --target=test --parallel=3

      - name: Build all
        run: npx nx run-many --target=build --parallel=3

      - name: Deploy angular app to firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NG_SOLID_RETAIL }}'
          channelId: live
          projectId: ng-solid-retail

      - name: Publish web api
        run: dotnet publish apps/solid-retail-api -c Release -o ${{env.DOTNET_ROOT}}/solid-retail-api

      - name: Upload be artifacts for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/solid-retail-api

  deploy_be:
    runs-on: ubuntu-latest
    needs: lint_test_build_affected
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ng-solid-retail'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D2DEC78A705D457DA8FB4839719C5FE3 }}
          package: .
